### ISSUE TITLE
Multiple issues with chunkwm & khd

### ISSUE THREAD

**Issue by gbuisson** [peel/dotfiles#9]
Greetings,

I'm trying to get `chunkwm` running using `darwin-nix`, your repo is the only to have an overlay including that I think.
I got it halfway running, I'm still facing some annoying issues:

- The download checksum for `chunkwm.core` is wrong
- The `chunkwm` plugins are not available at the advertised location,  I couldn't find any `/lib` folder under `/run/current-system`, I walk through that by setting the path to the tiling plugin under the nix store path, however I expect things to break after the next upgrade.
- troubleshooting `khd` I found out that your config cannot know about `chunkc`, it's not on the path I think, I replaced that with the real path under `/run/current-system` however I can get khd to run only if I invoke it by hand with he config file, it doesn't work as a service.

**Comment by peel** [comment]
Hey @gbuisson, sorry for the late reply. Thanks a bunch for the notice. 
I am not actively using darwin right now, so might have broken something along the lines. 
I've been using it up to https://github.com/peel/dotfiles/tree/9d51b3b9cd6c07235c012e064fa6e9d2a8b14a7a/nix/.nixpkgs/pkgs/os-specific/darwin/chunkwm I guess. Will have a look later today.

**Comment by gbuisson** [comment]
@peel , Thanks, I got everything running now.
- I fixed the checksum
- I kept the workaround for the plugins, will find a better solution later
- `khd` finds `chunkc` on the path just fine, I just had some issue with my shell settings
- I love your `emacs-mac` hack

It would be awesome if we could setup a new mac dev environment only using nix and skip brew, yet I find darwin support lacking, multi arch package definitions are somewhat messy IMO, perhaps creating a darwin nix channel/github repo would help.

**Comment by peel** [comment]
Had some other engagements throughout the month but finally got to do some business on a mac and solved the chunkwm issues/ugliness. The build is still impure but the rest of it seems to be fine. The caveat is that sadly the non-bin paths (chunkwm plugins) somehow failed to link to /run/current-system. Will follow up on that later on.

**Comment by kubek2k** [comment]
@gbuisson I think the issue is with the fact that the `chunkwm` module doesn't really install the actual chunkwm derivations. The way to overcome that is to add `pkgs.chunkwm.core` and desired plugins derivations straight into `environment.systemPackages`.

**Comment by gbuisson** [comment]
Yeah that’s what I ended up doing back then, it works fine now thank you.

**Comment by peel** [comment]
Yeah, it's not. As the package is not in nixpkgs the module uses literal example for package attribute. You either need to set module's package attribute or install declaratively through system packages. I released the package through NUR, in a bit, so it gets easier to get and supports cachix.

**Comment by kubek2k** [comment]
@gbuisson in the meantime you can use this [Rube Goldberg](https://pl.wikipedia.org/wiki/Rube_Goldberg)' solution: https://github.com/kubek2k/chunkwm.nix
